# Generated by Django 3.2 on 2021-04-28 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID для этого курса', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Введите название курса', max_length=255, verbose_name='Название курса')),
                ('start_date', models.DateField(help_text='Укажите дату начала курса', verbose_name='Начало курса')),
                ('end_date', models.DateField(help_text='Укажите дату окончания курса', verbose_name='Конец курса')),
                ('number_of_lectures', models.PositiveIntegerField(help_text='Укажите количество лекций', max_length=3, verbose_name='Количество лекций')),
                ('description', models.TextField(help_text='Добавьте описание курса', verbose_name='Описание курса')),
            ],
        ),
    ]
